import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const MANAGED_HEADER = "// AUTO-GENERATED by @kilog/nextjs-plugin — do not edit.";

interface Spec {
  path: string;
  managedContent: string;
  conflictHint: string;
}

const SERVER_SPEC: Spec = {
  path: "instrumentation.ts",
  managedContent: `${MANAGED_HEADER}
import { registerServer } from "@kilog/nextjs-plugin/register-server";

export async function register(): Promise<void> {
  await registerServer();
}
`,
  conflictHint: `add: import { registerServer } from "@kilog/nextjs-plugin/register-server"; and call await registerServer() from your existing register()`,
};

const CLIENT_SPEC: Spec = {
  path: "instrumentation-client.ts",
  managedContent: `${MANAGED_HEADER}
import "@kilog/nextjs-plugin/register-client";
`,
  conflictHint: `add: import "@kilog/nextjs-plugin/register-client";`,
};

const SIBLING_EXTENSIONS = [".ts", ".tsx", ".js", ".mjs", ".mts"];

function findExisting(projectRoot: string, basename: string): string | null {
  const stem = basename.replace(/\.ts$/, "");
  for (const ext of SIBLING_EXTENSIONS) {
    const candidate = join(projectRoot, stem + ext);
    if (existsSync(candidate)) return candidate;
  }
  return null;
}

function isManaged(path: string): boolean {
  try {
    return readFileSync(path, "utf8").startsWith(MANAGED_HEADER);
  } catch {
    return false;
  }
}

function ensureOne(projectRoot: string, spec: Spec): { conflict: string | null } {
  const found = findExisting(projectRoot, spec.path);

  if (found == null) {
    writeFileSync(join(projectRoot, spec.path), spec.managedContent);
    return { conflict: null };
  }

  // We own it — overwrite only if content drifted, to avoid mtime churn.
  if (isManaged(found)) {
    if (readFileSync(found, "utf8") !== spec.managedContent) {
      writeFileSync(found, spec.managedContent);
    }
    return { conflict: null };
  }

  return { conflict: `[kilog] found existing ${found} — ${spec.conflictHint}` };
}

export interface EnsureResult {
  conflicts: string[];
}

/**
 * Materializes `instrumentation.ts` and `instrumentation-client.ts` at the
 * project root if absent. If the user already authored either file, returns
 * a conflict hint per file rather than auto-editing — the user must add the
 * one-line import themselves.
 *
 * Files we own carry a `MANAGED_HEADER` so subsequent runs can rewrite them
 * without touching user code.
 */
export function ensureInstrumentation(projectRoot: string): EnsureResult {
  const conflicts: string[] = [];
  for (const spec of [SERVER_SPEC, CLIENT_SPEC]) {
    const { conflict } = ensureOne(projectRoot, spec);
    if (conflict != null) conflicts.push(conflict);
  }
  return { conflicts };
}
