import { describe, it, expect, beforeEach, afterEach } from "vite-plus/test";
import { mkdtemp, rm } from "node:fs/promises";
import { existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { withKilog } from "./with-kilog.js";

const PORT_ENV = "__KILOG_NEXTJS_PORT__";

describe("withKilog", () => {
  let projectRoot: string;
  let prevCwd: string;
  let prevNodeEnv: string | undefined;

  beforeEach(async () => {
    projectRoot = await mkdtemp(path.join(tmpdir(), "kilog-next-"));
    prevCwd = process.cwd();
    process.chdir(projectRoot);
    prevNodeEnv = process.env.NODE_ENV;
    delete process.env[PORT_ENV];
  });

  afterEach(async () => {
    process.chdir(prevCwd);
    if (prevNodeEnv == null) delete process.env.NODE_ENV;
    else process.env.NODE_ENV = prevNodeEnv;
    delete process.env[PORT_ENV];
    await rm(projectRoot, { recursive: true, force: true });
  });

  it("in non-dev mode: leaves rewrites alone, but still sets serverExternalPackages", () => {
    process.env.NODE_ENV = "production";
    const userRewrites = () => Promise.resolve([]);
    const wrapped = withKilog({ reactStrictMode: true, rewrites: userRewrites });
    expect(wrapped.reactStrictMode).toBe(true);
    expect(wrapped.rewrites).toBe(userRewrites);
    expect(wrapped.serverExternalPackages).toContain("@duckdb/node-api");
    expect(wrapped.serverExternalPackages).toContain("@kilog/register");
    expect(existsSync(path.join(projectRoot, "instrumentation.ts"))).toBe(false);
    expect(existsSync(path.join(projectRoot, "instrumentation-client.ts"))).toBe(false);
  });

  it("in dev mode, generates instrumentation files and adds the rewrite", async () => {
    process.env.NODE_ENV = "development";
    const wrapped = withKilog({ reactStrictMode: true });
    expect(typeof wrapped.rewrites).toBe("function");

    const rewrites = await (wrapped.rewrites as () => Promise<unknown>)();
    expect(Array.isArray(rewrites)).toBe(true);
    const arr = rewrites as Array<{ source: string; destination: string }>;
    expect(arr).toHaveLength(1);
    expect(arr[0].source).toBe("/__kilog");
    expect(arr[0].destination).toMatch(/^http:\/\/127\.0\.0\.1:\d+\/__kilog$/);

    expect(existsSync(path.join(projectRoot, "instrumentation.ts"))).toBe(true);
    expect(existsSync(path.join(projectRoot, "instrumentation-client.ts"))).toBe(true);
    expect(existsSync(path.join(projectRoot, ".gitignore"))).toBe(true);
  });

  it("merges with an existing rewrites array", async () => {
    process.env.NODE_ENV = "development";
    const wrapped = withKilog({
      rewrites: () => Promise.resolve([{ source: "/foo", destination: "/bar" }]),
    });
    const rewrites = (await (wrapped.rewrites as () => Promise<unknown>)()) as Array<{
      source: string;
    }>;
    expect(rewrites.map((r) => r.source)).toEqual(["/foo", "/__kilog"]);
  });

  it("merges with an existing rewrites object (afterFiles)", async () => {
    process.env.NODE_ENV = "development";
    const wrapped = withKilog({
      rewrites: () => Promise.resolve({ afterFiles: [{ source: "/x", destination: "/y" }] }),
    });
    const rewrites = (await (wrapped.rewrites as () => Promise<unknown>)()) as {
      afterFiles: Array<{ source: string }>;
    };
    expect(rewrites.afterFiles.map((r) => r.source)).toEqual(["/x", "/__kilog"]);
  });

  it("re-uses the cached port across rewrites() invocations", async () => {
    process.env.NODE_ENV = "development";
    const wrapped = withKilog({});
    const a = (await (wrapped.rewrites as () => Promise<unknown>)()) as Array<{
      destination: string;
    }>;
    const b = (await (wrapped.rewrites as () => Promise<unknown>)()) as Array<{
      destination: string;
    }>;
    expect(a[0].destination).toBe(b[0].destination);
  });

  it("uses the managed header in generated instrumentation files", async () => {
    process.env.NODE_ENV = "development";
    const wrapped = withKilog({});
    await (wrapped.rewrites as () => Promise<unknown>)();
    const server = readFileSync(path.join(projectRoot, "instrumentation.ts"), "utf8");
    const client = readFileSync(path.join(projectRoot, "instrumentation-client.ts"), "utf8");
    expect(server).toContain("AUTO-GENERATED by @kilog/nextjs-plugin");
    expect(server).toContain("@kilog/nextjs-plugin/register-server");
    expect(client).toContain("AUTO-GENERATED by @kilog/nextjs-plugin");
    expect(client).toContain("@kilog/nextjs-plugin/register-client");
  });
});
